# Generated by Django 5.0.6 on 2024-05-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('role', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('specialization', models.TextField(null=True)),
                ('institution', models.TextField(null=True)),
            ],
        ),
    ]
